version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./test:/var/lib/mysql
      - ./bbdd:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Casino
      MYSQL_USER: prueba
      MYSQL_PASSWORD: 123456
    ports:
      - 3307:3306
    cap_add:
      - SYS_NICE
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
  web:
    depends_on:
      - db
    image: tomcat:10.0
    volumes:
      - ./ProyectoCasino.war:/usr/local/tomcat/webapps/ProyectoCasino.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Casino
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456